[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "llvm-ar"
rustflags = [
  "-C",
  "link-arg=-Wl,-z,common-page-size=16384",
  "-C",
  "link-arg=-Wl,-z,max-page-size=16384",
]
